dist: trusty
os: linux
language: cpp

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
        packages:
            - libgtest-dev
    
before_script:
    - echo "before_script"
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: 
    - cmake -H. -B_builds && (cd _builds/ && make clean && make -j1 && make test)

after_success:
    - echo "success!"
