dist: trusty
os: linux
language: cpp

compiler:
    - gcc
    - clang

before_script:
    - echo "before_script"

script: 
    - cmake -H. -B_builds && (cd _builds/ && make clean && cmake --build .)

after_success:
    - echo "success!"
